### Get All categories
GET {{BASE_URL}}/categories HTTP/1.1

### Get Limited categories
GET {{BASE_URL}}/categories?page=2&limit=1 HTTP/1.1

### Get Searched categories
GET {{BASE_URL}}/categories/search?text=Electronics HTTP/1.1

### Create product
POST {{BASE_URL}}/categories/create HTTP/1.1
Content-Type: application/json

{
    "name": "clothing"
}

### Update product
PUT {{BASE_URL}}/categories/update HTTP/1.1
Content-Type: application/json

{
    "_id" : "62abeb5e7f5f2d7201c83c47",
    "name" : "electronics"
}

### Delete product
DELETE {{BASE_URL}}/categories/delete/62abeb917f5f2d7201c83c56 HTTP/1.1