### Get All products
GET {{BASE_URL}}/products HTTP/1.1

### Get Limited products
GET {{BASE_URL}}/products?page=2&limit=2 HTTP/1.1

### Get Searched products
GET {{BASE_URL}}/products/search?text=1 HTTP/1.1

### Create product
POST {{BASE_URL}}/products/create HTTP/1.1
Content-Type: application/json

{
    "name": "Mobile",
    "price": 100,
    "category": "62abeb5e7f5f2d7201c83c47"
}

### Update product
PUT {{BASE_URL}}/products/update HTTP/1.1
Content-Type: application/json

{
    "_id" : "62aa87946f74670927484e56",
    "category": "62abeb5e7f5f2d7201c83c47"
}

### Delete product
DELETE {{BASE_URL}}/products/delete/62abd8c70d04e2b637f85e20 HTTP/1.1