### Get All Users
GET {{BASE_URL}}/users HTTP/1.1

### Get Limited Users
GET {{BASE_URL}}/users?page=3&limit=2 HTTP/1.1

### Get Searched Users
GET {{BASE_URL}}/users/search?text=1 NewThing HTTP/1.1

### Create User
POST {{BASE_URL}}/users/create HTTP/1.1
Content-Type: application/json

{
    "displayName" : "Some Thing",
    "email" : "something@domain.com",
    "password" : "something_secret"
}

### Update User
PUT {{BASE_URL}}/users/update HTTP/1.1
Content-Type: application/json

{
    "_id" : "{{_id}}",
    "displayName" : "New Thing"
}

### Delete User
DELETE {{BASE_URL}}/users/delete/62a9387ab9b83a8f3add3808 HTTP/1.1